# Form implementation generated from reading ui file 'kalkulator.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(310, 460)
        font = QtGui.QFont()
        font.setPointSize(17)
        Form.setFont(font)
        Form.setStyleSheet("background-color: #213555;\n"
"color: white;")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 310, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 240, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 240, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 240, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_9.setGeometry(QtCore.QRect(160, 170, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_11.setGeometry(QtCore.QRect(20, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_12.setGeometry(QtCore.QRect(160, 380, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_13.setGeometry(QtCore.QRect(230, 309, 60, 131))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: #E5D283;\n"
"border-radius: 5px;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_14.setGeometry(QtCore.QRect(230, 169, 60, 131))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color: #E5D283;\n"
"border-radius: 5px;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_15.setGeometry(QtCore.QRect(230, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color: #E5D283;\n"
"border-radius: 5px;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_16.setGeometry(QtCore.QRect(160, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("background-color: #E5D283;\n"
"border-radius: 5px;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_17.setGeometry(QtCore.QRect(90, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("background-color: #E5D283;\n"
"border-radius: 5px;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 100, 60, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #4F709C;\n"
"border-radius: 5px;\n"
"padding: 10px;\n"
"text-align: right;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")

        #number button for display to label
        self.pushButton.clicked.connect(self.num1)
        self.pushButton_2.clicked.connect(self.num2)
        self.pushButton_3.clicked.connect(self.num3)
        self.pushButton_4.clicked.connect(self.num4)
        self.pushButton_5.clicked.connect(self.num5)
        self.pushButton_6.clicked.connect(self.num6)
        self.pushButton_7.clicked.connect(self.num7)
        self.pushButton_8.clicked.connect(self.num8)
        self.pushButton_9.clicked.connect(self.num9)
        self.pushButton_10.clicked.connect(self.num0)

        #operator button for display to label
        self.pushButton_13.clicked.connect(self.evaluate)
        self.pushButton_14.clicked.connect(self.add)
        self.pushButton_15.clicked.connect(self.subtract)
        self.pushButton_16.clicked.connect(self.multiply)
        self.pushButton_17.clicked.connect(self.divide)

        #point button
        self.pushButton_11.clicked.connect(self.point)

        #action button
        self.pushButton_12.clicked.connect(self.ac)
        self.pushButton_18.clicked.connect(self.back)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kalkulator"))
        self.pushButton.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_10.setText(_translate("Form", "0"))
        self.pushButton_11.setText(_translate("Form", "."))
        self.pushButton_12.setText(_translate("Form", "AC"))
        self.pushButton_13.setText(_translate("Form", "="))
        self.pushButton_14.setText(_translate("Form", "+"))
        self.pushButton_15.setText(_translate("Form", "-"))
        self.pushButton_16.setText(_translate("Form", "*"))
        self.pushButton_17.setText(_translate("Form", "/"))
        self.pushButton_18.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", ""))

    def point(self):
        number = self.label.text()
        self.label.setText(number+".")

    def num1(self):
        number = self.label.text()
        self.label.setText(number+"1")

    def num2(self):
        number = self.label.text()
        self.label.setText(number+"2")

    def num3(self):
        number = self.label.text()
        self.label.setText(number+"3")

    def num4(self):
        number = self.label.text()
        self.label.setText(number+"4")
    def num5(self):
        number = self.label.text()
        self.label.setText(number+"5")

    def num6(self):
        number = self.label.text()
        self.label.setText(number+"6")

    def num7(self):
        number = self.label.text()
        self.label.setText(number+"7")

    def num8(self):
        number = self.label.text()
        self.label.setText(number+"8")

    def num9(self):
        number = self.label.text()
        self.label.setText(number+"9")

    def num0(self):
        number = self.label.text()
        self.label.setText(number+"0")

    def evaluate(self):
        number = self.label.text()
        try:
            number = eval(number)
            number = str(number)
            self.label.setText(number)
        except Exception as o:
            self.label.setText("Input Salah")
    def add(self):
        number = self.label.text()
        self.label.setText(number + "+")

    def subtract(self):
        number = self.label.text()
        self.label.setText(number + "-")

    def multiply(self):
        number = self.label.text()
        self.label.setText(number + "*")

    def divide(self):
        number = self.label.text()
        self.label.setText(number + "/")

    def back(self):
        number = self.label.text()
        number = number[:-1]
        self.label.setText(number)

    def ac(self):
        self.label.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
